### PR TITLE
Setup the initial blog

### PR DESCRIPTION
**Pull request by michaelleii**

### CODE REVIEW

**Review by scottchen98 — APPROVED** [review]
nice set up

**Review by J3rryfan — APPROVED** [review]
good job

**Review by scottchen98 — APPROVED** [review]
all good to go

**Review by J3rryfan — APPROVED** [review]
love

**Review by J3rryfan — APPROVED** [review]

**Review by scottchen98 — APPROVED** [review]

**Review by J3rryfan — APPROVED** [review]

**Review by J3rryfan — APPROVED** [review]
love this good job

**Pull request merged**
